# Generated by Django 4.2.7 on 2026-04-05 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment (e.g., reason for referral).', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(help_text='The user who created this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mappings', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'ordering': ['-assigned_at'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
